server:
  port: 9999

eureka:
  client:
    service-url:
      default zone: http://localhost:8761/eureka/
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path= /order/**
          filters:
            - AuthenticationFilter
            - name : CircuitBreaker
              args:
                  name: callOrderFallback
                  fallbackUri: forward:/fallback/order

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path= /payment/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                 name: callOrderFallback
                 fallbackUri: forward:/fallback/payment

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path= /user/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: callOrderFallback
                fallbackUri: forward:/fallback/user



